language: java
services:
  - postgresql
before_script:
  - psql -c "CREATE USER 4hb3qijw ENCRYPTED PASSWORD '4hb3qijw';" -U postgres
  - psql -c "CREATE DATABASE sjzoatpd WITH OWNER = 4hb3qijw;" -U postgres
  - echo "localhost:5432:sjzoatpd:4hb3qijw:4hb3qijw" > ~/.pgpass
   
  