language: java
install: true
jdk:
  - openjdk10
services:
  - postgresql
addons:
  firefox: latest
before_script:
  - psql -c "CREATE USER nznz4fjn ENCRYPTED PASSWORD '3h6kov63tt4xvo8q';" -U postgres
  - psql -c "CREATE DATABASE sjzoatpd WITH OWNER = nznz4fjn;" -U postgres
  - echo "localhost:5432:sjzoatpd:nznz4fjn:3h6kov63tt4xvo8q" > ~/.pgpass
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar zxvf geckodriver-v0.21.0-linux64.tar.gz
  - rm geckodriver-v0.21.0-linux64.tar.gz
  - sudo mv -f geckodriver /usr/local/share/
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
script:
  - mvn clean verify
cache:
  directories:
  - $HOME/.m2
