language: java
install: true
jdk:
  - openjdk10
services:
  - postgresql
addons:
  firefox: latest
before_script:
  - psql -c "CREATE USER nznz4fjn ENCRYPTED PASSWORD '3h6kov63tt4xvo8q';" -U postgres
  - psql -c "CREATE DATABASE sjzoatpd WITH OWNER = nznz4fjn;" -U postgres
  - echo "localhost:5432:sjzoatpd:nznz4fjn:3h6kov63tt4xvo8q" > ~/.pgpass
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
  - mvn clean verify
cache:
  directories:
  - $HOME/.m2
